eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: baeldung
    password: baeldung
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
